---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "[DEV-OPS] (dependabot) "
    assignees:
      - HeeroYui

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Paris"
    commit-message:
      prefix: "[DEV-OPS] (dependabot) "
    assignees:
      - HeeroYui
    groups:
      junit:
        patterns:
          - "org.junit.jupiter:*"
      jackson:
        patterns:
          - "com.fasterxml.jackson.*:*"
      jersey:
        patterns:
          - "org.glassfish.jersey.*:*"
      mockito:
        patterns:
          - "org.mockito:*"
      slf4j:
        patterns:
          - "org.slf4j:*"
      logback:
        patterns:
          - "ch.qos.logback:*"
